---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: build-and-test
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - /root/entrypoint.sh
      - sbt test docker:stage
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
    when:
      event:
        - push

  - name: publish
    image: plugins/ecr
    environment:
      AWS_REGION: eu-west-2
    settings:
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      repo: drt/drt-api-import
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      tags:
        - B${DRONE_BUILD_NUMBER}
        - latest
    when:
      event:
        - push
    depends_on:
      - build-and-test

  - name: Slack notification
    pull: if-not-exists
    image: plugins/slack
    settings:
      channel: devs
      template: "*{{repo.name}}: _{{build.status}}_*\nCompleted build *{{build.number}}* after *{{since build.started}}* on *{{build.branch}}*\n{{build.link}}\n"
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      status: [ success, failure ]
      event:
        - push
    depends_on:
      - publish

  - name: analysis
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - /root/entrypoint.sh
      - bash ./run_tests.sh
      - sbt scapegoat | true
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
      ENV_LOG_LEVEL: ERROR
    when:
      event:
        - push
    depends_on:
      - publish

  - name: Dependency check
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - /root/entrypoint.sh
      - sbt -Dlog4j2.level=info dependencyCheck
    environment:
      NVD_API_KEY:
        from_secret: NVD_API_KEY_SECRET
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
      ENV_LOG_LEVEL: ERROR
      KEYTOOL_PASSWORD:
        from_secret: KEYTOOL_PASSWORD
    when:
      event:
        - push
      branch:
        - master
    depends_on:
      - analysis

  - name: sonar-scanner
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/sonar-scanner:v7.3
    commands:
      - sonar-scanner -Dsonar.projectVersion=B${DRONE_BUILD_NUMBER}
    environment:
      DRONE_BUILD_NUMBER: ${DRONE_BUILD_NUMBER}
    when:
      event:
        - push
    depends_on:
      - Dependency check
...
